### ISSUE TITLE
Allow full URLs in ID/slug field

### ISSUE THREAD

**Issue by Madis0** [itssimple/WhatCurseForgeProjectIsThis#3]
Because people are lazy :stuck_out_tongue:

**Comment by itssimple** [comment]
Ah, like `https://www.cflookup.com/https://www.curseforge.com/minecraft/modpacks/too-many-projects`?

And then just deal with it internally? Sounds fair!

**Comment by itssimple** [comment]
Oh, right. I can fix that as well. ^^

**Comment by Madis0** [comment]
Not uploaded yet? I get this when I try
![image](https://user-images.githubusercontent.com/8611110/172044181-6e1ad9ac-6e25-49bd-a225-bd8375c2f7b9.png)

**Comment by itssimple** [comment]
Interesting.. it should have uploaded automatically. Let me give it a go.

**Comment by itssimple** [comment]
Ah.. when it gets an error like that, it's because the API times out. I'll see if I can do something about that.

**Comment by Madis0** [comment]
Ah yes, I can confirm that it sometimes works and sometimes times out.

**Comment by itssimple** [comment]
Yeah, it's because I use the "slow" version of slug search, (I basically reused the one in place for slugs, without game or class/category).

But I'll poke it and reuse the logic from the other endpoint, which takes those in mind and doesn't need to search everything.

**Comment by itssimple** [comment]
And it should be fixed now! ^^
