### ISSUE TITLE
Convert Issues, Wiki/Docs & Source to embed hyperlinks.

### ISSUE THREAD

**Issue by Claycorp** [itssimple/WhatCurseForgeProjectIsThis#4]
https://github.com/itssimple/WhatCurseForgeProjectIsThis/blob/f5ab06cf9646f09232b027f65865a63af57529ee/WhatCurseForgeProjectIsThis/Pages/CFEmbed.cshtml#L26

https://github.com/itssimple/WhatCurseForgeProjectIsThis/blob/f5ab06cf9646f09232b027f65865a63af57529ee/WhatCurseForgeProjectIsThis/Pages/CFEmbed.cshtml#L37

https://github.com/itssimple/WhatCurseForgeProjectIsThis/blob/f5ab06cf9646f09232b027f65865a63af57529ee/WhatCurseForgeProjectIsThis/Pages/CFEmbed.cshtml#L47

All of these are currently pasting raw URLs and projects can have long ass URLs pushing other info off the card. Embeds are the only thing that supports the `[Word](url)` markdown hyperlinking so placing the these within one should fix the issue with long URLs and make them clickable within the embed. These could likely be all be combined into a single line to make the size of the embedded info smaller as they are rather chunky with all the current information listed due the data dence nature of them.

Example Issue case: 
![image](https://user-images.githubusercontent.com/3961359/172035380-61f28e3b-22d6-4b60-ace4-ec1f74b7abd8.png)

Test URL: https://www.cflookup.com/minecraft/mc-mods/tfcraft

(I'd do this myself but have nothing set up for a work space like this to fix it or test it :P)

Edit: I am aware this is only a discord feature but as we are primarily targeting discord it should be fine and honestly most stuff is likely going to support markdown embeds and if they don't it doesn't really add to the overall length of the embed. Just looks a bit odd.

**Comment by itssimple** [comment]
I can make so that only Discord gets those types of links (to see if it works). :)

**Comment by itssimple** [comment]
Apparently, links like that doesn't work in embeds.
![image](https://user-images.githubusercontent.com/11502257/172039951-60dda12e-f73b-4d3e-a7e9-d2731785eaef.png)

**Comment by itssimple** [comment]
Might have found a way, if I use oEmbed as well, I can provide a small HTML snippet instead.

**Comment by itssimple** [comment]
Getting closer, but still no way to get links in there.
![image](https://user-images.githubusercontent.com/11502257/172042700-d0f82ae8-057e-4842-8624-d1ffc221cdd0.png)

It "should" work, since I'm using the oembed with "rich" type, that should support HTML.

But I guess Discord doesn't support it.

**Comment by itssimple** [comment]
From what I understand, only bots are able to do those types of links in embeds

**Comment by Claycorp** [comment]
Discord, what geniuses....

**Comment by itssimple** [comment]
(I also reverted to use small images, it was not received with happy responses :P)
