### ISSUE TITLE
slug lookups don't work

### ISSUE THREAD

**Issue by DioEgizio** [itssimple/WhatCurseForgeProjectIsThis#5]
Try to enter a slug and see

![image](https://user-images.githubusercontent.com/83089242/174124400-b65d9820-346b-4b7b-89ab-6633edf6494d.jpg)

**Comment by itssimple** [comment]
Could very well be that it's getting a timeout against the API.

Preferred is to post the entire URL from CF, as it will make a smaller search like that.
(It parses game, class and slug)

**Comment by itssimple** [comment]
Fixed some better handling and multithreading for slug searches, with some promising results. (Except when the API craps out, can't do much about that)
